newlist=[1,2,3,4,5,6]
print(newlist)
newlist.clear()
print(newlist)
thislist=["Apple","banana","cherry","jackfruite"]
print(thislist)
print(thislist.sort())
print(thislist.sort(reverse=True))
thislist.sort(reverse=True)
print(thislist)
